### ISSUE TITLE
Clarify how fastify-cookie settings interacti with fastify-session settings

### ISSUE THREAD

**Issue by bcomnes** [SerayaEryn/fastify-session#169]
I'm setting up fastify-session for the first time, and I'm uncertain how `fastify-cookie` settings overlap with `fastify-session` settings.  

Like should I also set the secret and used signed cookies in `fastify-cookie`? Does that interfere with the secret or cookie signing in this module? 

A quick addition to the readme would really help out here I think.  Happy to write something up once I figure this out.  In the meantime, any pointers appreciated.

**Comment by mfpopa** [comment]
You do not need to set any options for `fastify-cookie`. In fact, if you do they'll be overwritten by the `fastify-session` cookie options. Just register the plugin before the `fastify-session` plugin like it's shown in the README and then set any session and cookie options you need to the `fastify-session` plugin.

You may need to set options on the `fastify-cookie` plugin when you want custom cookies for your application, or if you use/build a different implementation for managing user authentication sessions.

Note that you'll need a custom store for the `store` option so that you can save user sessions to a DB (e.g. Redis, Mongo). The default store provided by `fastify-session` is an in-memory store, which means that user sessions are persisted only as long as you do not restart the OS process running your application or the server.

You may also want to set `saveUninitialized: false` to avoid creating sessions in the DB for unauthenticated users.

**Comment by bcomnes** [comment]
Thanks for the clarification! Sorry this was sitting in my read GitHub inbox for ages, I just re-discovered it. Closing
